[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Enable the Solidity optimizer
optimizer = true
optimizer_runs = 200

# Enable the IR pipeline to help with stack too deep errors
via_ir = true

# Enable extra optimization steps
# This can help reduce contract size and improve gas efficiency
[profile.default.optimizer_details]
yul = true

[profile.default.optimizer_details.yul_details]
optimizer_steps = "u"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
